[workspace]
members = [
    "lemao-bindgen",
    "lemao-core",
    "lemao-math",
    "lemao-openal",
    "lemao-opengl",
    "lemao-winapi",

    "examples/audio",
    "examples/benchmark",
    "examples/line",
    "examples/transformation",
    "examples/window",
]