[package]
name = "lemao-core"
version = "1.0.0"
edition = "2021"

[dependencies]
lemao-math = { path = "../lemao-math" }
lemao-openal = { path = "../lemao-openal" }
lemao-opengl = { path = "../lemao-opengl", features = [ "windows" ] }
lemao-winapi = { path = "../lemao-winapi" }
