[package]
name = "line"
version = "1.0.0"
edition = "2021"

[dependencies]
lemao-core = { path = "../../lemao-core" }
lemao-ui = { path = "../../lemao-ui" }
chrono = { version = "0.4.22" }
fastrand = { version = "1.8.0" }
